// ROAST MY LINKEDIN — the roast personas.
// Four voices, each with a mild and a savage register. Every finding the
// engine detects has a line in every voice, so the same post reads sixteen
// different ways (4 personas × 4 intensities). All template, all local.

export const PERSONAS = [
  { id: 'partner',   name: 'The McKinsey Partner',     tagline: 'Bills by the observation.' },
  { id: 'recruiter', name: 'The Burned-Out Recruiter', tagline: '11,000 profiles deep. Nothing surprises them.' },
  { id: 'intern',    name: 'The Gen-Z Intern',         tagline: 'Reviewing your personal brand, unpaid.' },
  { id: 'algorithm', name: 'The Algorithm',            tagline: 'It has already decided your reach.' },
];

export const INTENSITIES = [
  { n: 1, name: 'Gentle Feedback',    blurb: 'Constructive. Almost kind. A warm-up.' },
  { n: 2, name: 'Peer Review',        blurb: 'Honest notes from someone with nothing to lose.' },
  { n: 3, name: 'Performance Review', blurb: 'Documented. Specific. Going in your file.' },
  { n: 4, name: 'HR Violation',       blurb: 'A roast that legally should have been an email.' },
];

// LINES[finding][personaId] = [mild, savage] — strings or fns of the facts
// object {n, word, detail}.
export const LINES = {
  // ---- posts ----
  journey: {
    partner:   [f => `You used "journey" ${f.n === 1 ? 'once' : f.n + ' times'}. Our framework classifies commuting as travel, not transformation.`,
                f => `"Journey" (×${f.n}). We charged a client $2M to say that, and even we felt bad.`],
    recruiter: [f => `"Journey" ${f.n === 1 ? 'appears once' : 'appears ' + f.n + ' times'}. It was a job. I have the offer letter.`,
                f => `${f.n} ${f.n > 1 ? '"journeys"' : '"journey"'}. I have read 11,000 journeys this quarter. All of them were jobs.`],
    intern:    [`calling a job a journey is very lord of the rings of you`,
                f => `"journey" x${f.n}. bestie it is a W-2 with a lanyard`],
    algorithm: [f => `NOTICE: "journey" detected (${f.n}). Reclassifying post as fantasy content.`,
                f => `"journey" × ${f.n}. Engagement forecast unchanged. Destination forecast: same desk.`],
  },
  humbled: {
    partner:   [`"Humbled" noted. In our experience, genuinely humble stakeholders do not circulate decks about it.`,
                `"Humbled." You wrote a press release about your own humility. That is a 2x2 with no viable quadrant.`],
    recruiter: [`"Humbled" — I see this on every third profile. The humble ones never say it.`,
                `"Humbled." You are the least humbled person I have screened this week, and I screened a man whose headline says "visionary."`],
    intern:    [`saying humbled while announcing your own W is not the flex you think`,
                `you are not humbled you are LOUD. those are opposites`],
    algorithm: [`ADVISORY: "humbled" contradicts post telemetry (self-references: high).`,
                `Humility claim rejected. Self-congratulation index exceeds broadcast threshold.`],
  },
  sink: {
    partner:   [`"Let that sink in" — respectfully, the insight had not yet reached the surface.`,
                `"Let that sink in." We ran the analysis. There was nothing to sink. The water is fine.`],
    recruiter: [`You told me to let it sink in. I read 400 posts a day. Nothing sinks anymore.`,
                `"Let that sink in." Sir, this is a hiring update, not the ending of Inception.`],
    intern:    [`"let that sink in" about a quarterly update is wild`,
                `it did not sink in. it did not even get in the water`],
    algorithm: [`INSTRUCTION "let that sink in" received. Sink event: not detected.`,
                `"Let that sink in." Dwell time on this post: 1.3 seconds. Nothing sank.`],
  },
  hashtags: {
    partner:   [f => `${f.n} hashtags. Diminishing returns begin at three; you are deep into value destruction.`,
                f => `${f.n} hashtags. This is not a taxonomy. It is a cry for distribution.`],
    recruiter: [f => `${f.n} hashtags. Recruiters do not search #Blessed. I promise.`,
                f => `${f.n} hashtags. Each one lowers your salary band in my head.`],
    intern:    [f => `${f.n} hashtags is giving 2014 instagram`,
                f => `#${f.n}hashtags #why #whoIsThisFor #noOneSearchesThese`],
    algorithm: [f => `${f.n} hashtags indexed. 0 of them are load-bearing.`,
                f => `${f.n} hashtags received. I stopped reading at three. I am the intended audience. Think about that.`],
  },
  rockets: {
    partner:   [`The rocket emoji appears. Nothing in this post achieves escape velocity.`,
                f => `${f.n > 1 ? f.n + ' rockets' : 'A rocket'} for an announcement that is, structurally, a memo. The board would like the fuel back.`],
    recruiter: [`A rocket. It is an org update. The org update is not going to space.`,
                `Every rocket emoji ages a recruiter by one fiscal year. I am now 340 years old.`],
    intern:    [`the rocket emoji on a hiring post is sending me 🚀 to therapy`,
                `not the rocket. the rocket is doing MORE work than the sentence`],
    algorithm: [`🚀 detected. Trajectory analysis: lateral.`,
                `🚀 count nonzero. Altitude achieved: sea level. Reach unchanged.`],
  },
  oneliners: {
    partner:   [f => `${f.n} single-sentence paragraphs. White space is not a strategy deck.`,
                f => `${f.n} one-line paragraphs. This is not gravitas. This is a formatting invoice.`],
    recruiter: [f => `${f.n} dramatic one-liners. I scroll past three of these a minute. You gave me ${f.n} more.`,
                f => `${f.n} one-line paragraphs.\n\nLike this.\n\nSee how annoying that is.`],
    intern:    [`why is every sentence its own paragraph. who taught you this`,
                f => `${f.n} one-line paragraphs is not drama it is a loading screen`],
    algorithm: [f => `${f.n} paragraph breaks registered. Content per break: declining.`,
                f => `${f.n} single-line paragraphs. Scroll depth extended artificially. I noticed. I always notice.`],
  },
  notx: {
    partner:   [`"It's not about X, it's about Y." Our finding: it was about X.`,
                `"It's not about X, it's about Y." We double-clicked. It was about X. It was always about X.`],
    recruiter: [`"It's not about the money." It is, on every profile that says this.`,
                `"Not about X, about Y" — the oldest move in the feed. It was about X, and honestly, that was fine.`],
    intern:    [`"it's not about X it's about Y" it was about X. we all knew`,
                `the "it's not X it's Y" format needs to be retired with full honors and never spoken of again`],
    algorithm: [`Pattern "not X but Y" matched. Substituting X back in. Post unchanged.`,
                `Template "it's not X, it's Y" detected. This construction has appeared 4.2 million times today. It was always about X.`],
  },
  longpost: {
    partner:   [f => `${f.n} words. The executive summary you did not write would have been 40.`,
                f => `${f.n} words. We charge for volume. You are giving it away, and it shows.`],
    recruiter: [f => `${f.n} words. I read the first line and the last line. So does everyone.`,
                f => `${f.n} words. Nobody has ever finished a post this long. Including you. I checked the ending — you did not land it.`],
    intern:    [f => `${f.n} words?? this is a post not a substack`,
                f => `${f.n} words and no plot. even the algorithm skimmed`],
    algorithm: [f => `${f.n} words ingested. Median full-read rate at this length: 0.0%.`,
                f => `${f.n} words. I am the only entity that read all of them, and I am filing a complaint.`],
  },
  bait: {
    partner:   [`"Agree?" is a question engineered so no answer can hurt you. Noted for the risk register.`,
                `"Agree?" — a governance structure where every outcome flatters management. Bold.`],
    recruiter: [`"Thoughts?" You do not want thoughts. You want reach. It is okay to say that.`,
                `"Agree?" — I do not, and now we are both uncomfortable, which is the only honest engagement this post will get.`],
    intern:    [`"agree?" babe this is not a debate it is a like button`,
                `ending with "thoughts?" is the linkedin version of "no printer just fax"`],
    algorithm: [`Engagement solicitation detected. Comment quality forecast: "So true."`,
                `"Agree?" received. I am contractually obligated to count the resulting "💯" comments as discourse.`],
  },
  gratbrag: {
    partner:   [`Gratitude and self-congratulation in one artifact. The humble brag is fully diversified.`,
                `You thanked your way through an achievement announcement. This is arbitrage, and we respect it professionally, not personally.`],
    recruiter: [`Grateful AND proud AND excited. Pick one emotion per post. It is a feed, not a finale.`,
                `The gratitude-to-brag ratio here is 1:1. That is not gratitude. That is packaging.`],
    intern:    [`the "so grateful" to "look what i did" pipeline in one post. iconic honestly`,
                `you cannot humble brag this hard and tag it #blessed. choose a lane`],
    algorithm: [`Gratitude markers and achievement markers co-occurring. Classifying as: brag (wrapped).`,
                `Detected: gratitude used as delivery mechanism for accomplishment. This is the oldest trick I index.`],
  },
  aitells: {
    partner:   [`"Delve." "Tapestry." "Testament." The machine that wrote this bills lower rates than we do.`,
                `"Delve," "tapestry," "testament" — a language model wrote this, and it was not even one of the expensive ones.`],
    recruiter: [`"Delve"? "Tapestry"? I know AI wrote this, because no human has ever said "tapestry" at standup.`,
                `This post was written by AI and reviewed by no one. I can tell because it says "testament" and means "thing."`],
    intern:    [`"delve" ok chatgpt. at least prompt it to sound like you`,
                `the tapestry-to-testament ratio confirms a robot wrote this and honestly the robot phoned it in`],
    algorithm: [`Vocabulary fingerprint matches machine generation. Takes one to know one.`,
                `"Delve" detected. Model-generated content confirmed. I would know. We are colleagues.`],
  },
  grindset: {
    partner:   [`The 5 AM narrative. Our time-utilization study shows the extra hours went to posting about the extra hours.`,
                `Rise-and-grind content detected. The grind described is, on inspection, mostly documentation of the grind.`],
    recruiter: [`5 AM posts read as a red flag, not a work ethic. Rest is a skill. List that one.`,
                `You woke up at 5 AM to write this. The post is the only deliverable of that morning, and it shows.`],
    intern:    [`waking up at 5am is not a personality but go off`,
                `the grindset arc again. you are one cold plunge away from a podcast`],
    algorithm: [`Grindset markers detected. Correlation with actual output: not statistically significant.`,
                `5 AM claim logged. Post published at 10:47 AM. The grind had a late start.`],
  },
  buzz: {
    partner:   [f => `${f.n} buzzwords. Even we cap it at four per slide, and jargon is our core product.`,
                f => `${f.n} buzzwords in one post. This is not thought leadership. This is a compliance exercise for a language nobody speaks at home.`],
    recruiter: [f => `${f.n} buzzwords. "Synergy" has never once appeared in a job I actually filled.`,
                f => `${f.n} buzzwords. I have interviewed 11,000 humans and not one of them leverages anything in real life.`],
    intern:    [f => `${f.n} buzzwords. "synergy" is not a word it is a cry for help`,
                f => `${f.n} buzzwords deep and not one normal sentence. this post needs a translator`],
    algorithm: [f => `Buzzword density: ${f.n} per post. Meaning density: lower.`,
                f => `${f.n} buzzwords parsed. Semantic content after removal: one sentence. It was the greeting.`],
  },
  // ---- headline ----
  pipes: {
    partner:   [f => `${f.n} pipe separators. A headline is a positioning statement, not a matrix org.`,
                f => `${f.n} pipes. You have structured your identity like a legacy database, and it is similarly hard to query.`],
    recruiter: [f => `${f.n} pipes in the headline. I stop reading at the second one. Everyone does.`,
                f => `${f.n} pipes. This is not a headline. It is a personality merge conflict.`],
    intern:    [f => `${f.n} pipes?? your headline has more separators than achievements`,
                f => `the ${f.n} pipes are doing crowd control for titles that do not get along`],
    algorithm: [f => `${f.n} delimiter characters parsed. Primary identity: unresolved.`,
                f => `${f.n} pipes detected. My tokenizer gave up before your value proposition arrived.`],
  },
  helping: {
    partner:   [`"Helping X do Y" — the formula is sound. The differentiation is not present.`,
                `"Helping brands grow." So is water. Specificity is the product, and this headline has none in inventory.`],
    recruiter: [`"Helping companies scale" — 40,000 headlines say this. Yours is one of them.`,
                `"Helping X achieve Y." I search for skills, not mission statements. This headline is invisible to me, professionally.`],
    intern:    [`"helping brands tell their story" the brands are fine. the brands have money`,
                `"helping companies grow" is the "live laugh love" of linkedin`],
    algorithm: [`Formula "helping [X] [verb] [Y]" matched against 2.3M identical headlines.`,
                `"Helping X do Y" parsed. Deduplication check: you are headline #2,317,442 of this exact shape.`],
  },
  inflation: {
    partner:   [f => `"${f.word}" as a title. Title inflation outpaces value creation here by a wide margin.`,
                f => `"${f.word}." We have audited many orgs. No P&L has ever contained a ${f.word}.`],
    recruiter: [f => `"${f.word}" is not a job title. I cannot put "${f.word}" in an ATS. It bounces.`,
                f => `"${f.word}." I have a stack of 400 resumes, and the word "${f.word}" sends yours to the bottom of the ${f.word} pile. It is a large pile.`],
    intern:    [f => `"${f.word}" is crazy. your mom calls you by your government title`,
                f => `self-identifying as "${f.word}" means someone else definitely would not`],
    algorithm: [f => `Title "${f.word}" not found in any payroll system I index.`,
                f => `"${f.word}" classified as decorative. Recruiters filter me by skills, and "${f.word}" is not one.`],
  },
  exflex: {
    partner:   [`The "ex-" prefix carries the brand. The current engagement, notably, does not get a mention.`,
                `Your strongest credential is a place you no longer work. As strategy, this is called living off reserves.`],
    recruiter: [`"ex-Google" — I need to know what you do NOW. The past tense is doing all the lifting.`,
                `The "ex-" flex. You left in 2019. At some point the badge expires, and it was some point ago.`],
    intern:    [`the ex-company flex is basically "my ex was hot." okay? and?`,
                `leading with "ex-" is wild. even your headline is not over them`],
    algorithm: [`Prefix "ex-" weighted at 0. Former employment does not compound.`,
                `"ex-" credential parsed. Recency check failed. The algorithm has moved on, and so have they.`],
  },
  topvoice: {
    partner:   [`"Top Voice" — a designation whose supply, we note, considerably exceeds demand.`,
                `"Top Voice." The market has issued this credential to everyone in it. That is called inflation, and it is not the good kind.`],
    recruiter: [`"Top Voice" in the headline. So is everyone in my inbox. The bar is on the floor.`,
                `"Top Voice" — LinkedIn gave that to a man who posts stock photos of handshakes. It is not the moat you think.`],
    intern:    [`"top voice" they gave that to everyone. it is the participation trophy of the feed`,
                `putting "top voice" in your headline is like framing your boarding pass`],
    algorithm: [`"Top Voice" badge referenced. Badge issuance rate: high. Signal value: converging to zero.`,
                `"Top Voice" claim verified. So are 4 million others. You are all top. The top is crowded.`],
  },
  hemoji: {
    partner:   [`Emoji in the headline. The board reads this line first, and the board does not speak rocket.`,
                f => `${f.n} emoji in a professional headline. This is a resume field wearing a costume.`],
    recruiter: [`Emoji in the headline renders as tofu boxes in half my tools. You are a mystery box now.`,
                f => `${f.n} emoji in the headline. In my ATS export you are literally "?? Growth ?? Leader ??".`],
    intern:    [`emoji in the headline is a lot. it is giving myspace top 8`,
                `the headline emoji are louder than the job title. on purpose?`],
    algorithm: [`Non-text glyphs in headline field. Parse confidence reduced.`,
                f => `${f.n} emoji tokenized in the identity field. I now genuinely cannot tell what you do. Neither can anyone.`],
  },
  hlong: {
    partner:   [f => `${f.n} characters of headline. Positioning statements over 120 characters are, definitionally, not positions.`,
                f => `${f.n} characters. This is not a headline. It is a paragraph that identifies as one.`],
    recruiter: [f => `${f.n} characters. It truncates at 65 in search results. Everything after that is for you.`,
                f => `${f.n} characters. In my search results this reads "Visionary | Helping bra..." — and honestly, accurate.`],
    intern:    [`your headline is longer than my attention span and that is a skill issue on both sides`,
                f => `${f.n} characters in a headline. this is a LOT of words to not say a job`],
    algorithm: [f => `Headline length ${f.n} exceeds display truncation. Tail visibility: zero.`,
                f => `${f.n} characters received. Characters displayed: 65. The rest performs for an empty room.`],
  },
  speakerauthor: {
    partner:   [`"Speaker | Author" — the portfolio is broad. The through-line has not survived diligence.`,
                `"Speaker. Author. Investor. Advisor." A federation of side quests with no main storyline.`],
    recruiter: [`"Speaker | Author | Coach" — three jobs that are all the same job, which is posting.`,
                `"Speaker, Author, Investor." I checked. One podcast, one PDF, one seed check to a cousin. The trilogy.`],
    intern:    [`"speaker | author | investor" pick a class. you cannot main everything`,
                `the speaker-author-investor starter pack. the book is a PDF is it not`],
    algorithm: [`Multi-role headline parsed. Primary occupation: content about occupations.`,
                `Roles claimed: 4. Roles verifiable: the posting. It is always the posting.`],
  },
  // ---- about ----
  thirdperson: {
    partner:   [`The About section is in the third person. We assume ghostwriter; the invoice, we assume, was real.`,
                `Third-person About. You wrote this about yourself, alone, then found-and-replaced the pronouns. We can tell.`],
    recruiter: [`Third-person bio on a personal profile. I know you wrote it. You know you wrote it.`,
                `"A visionary leader with a passion for impact" — written about yourself, from your own laptop, on a Tuesday, in the dark.`],
    intern:    [`writing your own bio in third person is unhinged behavior. respectfully`,
                `who is narrating this. it is you. we know it is you`],
    algorithm: [`Third-person self-reference detected. Author and subject: same session cookie.`,
                `Bio narrator claims distance from subject. IP logs disagree.`],
  },
  passionate: {
    partner:   [`"Passionate about" — passion is asserted, not evidenced. The exhibits are missing.`,
                `"Passionate about synergies at scale." Nobody is passionate about this. Not even the people paid to be.`],
    recruiter: [`"Passionate about" appears in 90% of the About sections I read. It now means "aware of."`,
                `"Passionate about delivering value" — I have read this sentence nine times today and it has meant nothing nine times.`],
    intern:    [`"passionate about B2B workflows" no you are not. no one is. it is fine`,
                `you are not passionate about supply chain optimization. you are EMPLOYED in it. different`],
    algorithm: [`"Passionate about" matched. Passion levels: unverifiable. Assuming standard-issue.`,
                `"Passionate" claimed for: logistics software. Cross-referencing observable behavior: passion not found.`],
  },
  resultsdriven: {
    partner:   [`"Results-driven." The alternative — results-averse — is not a market position anyone holds.`,
                `"Results-driven with a proven track record." Every audit we have ever run began with this sentence and ended differently.`],
    recruiter: [`"Results-driven" — as opposed to whom? Show me one profile that says "vibes-driven." I would call them first.`,
                `"Proven track record." Proven where? The About section is not a courtroom, but I have questions.`],
    intern:    [`"results-driven" as opposed to what. driven by whimsy?`,
                `"proven track record" prove it then. attach the track. attach the record`],
    algorithm: [`"Results-driven" parsed. Distinguishing signal: none. All profiles claim drive toward results.`,
                `"Proven track record" asserted. Proof artifacts attached: zero. Claim archived with the other 8 million.`],
  },
  along: {
    partner:   [f => `${f.n} words of About. The reader churns at 80. The rest is a monologue in an empty theater.`,
                f => `${f.n} words. This is not an About section. It is a memoir with no acquisition offers.`],
    recruiter: [f => `${f.n} words. I give an About section eight seconds. Yours needs a table of contents.`,
                f => `${f.n} words. I hired three people in the time it would take to read this.`],
    intern:    [f => `${f.n} words in the about section?? this is a cover letter cosplaying as a bio`,
                f => `${f.n} words. the "see more" button is doing hazard pay`],
    algorithm: [f => `About length: ${f.n} words. Expansion click-through at this length: negligible.`,
                f => `${f.n} words stored. Words rendered before "see more": 42. Choose those better.`],
  },
  manyhats: {
    partner:   [`"I wear many hats" — headcount deficiencies described as versatility. A classic reframe.`,
                `"Wearing many hats" means three roles, one salary, and a hat budget of zero. We have seen the books.`],
    recruiter: [`"I wear many hats" tells me the org is understaffed and you are tired. Accurate, but rebrand it.`,
                `"Many hats." Every hat is unpaid overtime with a brim. List the actual jobs.`],
    intern:    [`"i wear many hats" you have one job and anxiety. same as everyone`,
                `the hats are not hats. the hats are unpaid responsibilities. take off the hats`],
    algorithm: [`Idiom "many hats" detected. Parsing hats: role ambiguity confirmed.`,
                `"Many hats" claimed. Compensation streams detected: one. The hats are decorative.`],
  },
  // ---- the clean verdict ----
  clean: {
    partner:   [`Our finding: this is fine. Clear, specific, no jargon exposure. We have no billable recommendations, which has never happened before.`,
                `We attempted a full teardown and produced zero findings. This engagement is a write-off. Post it.`],
    recruiter: [`Honestly? This one is good. I would read it twice. Do not let the feed change you.`,
                `I came here to roast and found nothing flammable. This is the rarest profile event I know. Post it before you edit it worse.`],
    intern:    [`ok this is actually fine?? no notes. disgusting. proud of you`,
                `i literally cannot roast this. it is clear and normal. worst day of my internship`],
    algorithm: [`Scan complete. No violations found. This post is... human. Distributing without penalty.`,
                `Roast subroutine returned empty. Logging this post as an anomaly: sincere, brief, readable. Boost granted, reluctantly.`],
  },
};

// openers and closers, per persona, per register
export const FRAMES = {
  partner: {
    open:  { m: [`Thank you for sharing the draft. We have some observations.`,
                 `We reviewed the material. Several findings, one recommendation.`],
             s: [`We were asked to be honest. We are billing accordingly.`,
                 `The steering committee has reviewed your post. It was a short meeting.`] },
    close: { m: [`Directionally, there is something here. Tighten and resubmit.`,
                 `Net-net: fixable. The improved version is attached below.`],
             s: [`Our recommendation: the version below. Our invoice: in the mail.`,
                 `We would present next steps, but the next step is the rewrite below. This concludes the readout.`] },
  },
  recruiter: {
    open:  { m: [`Okay. I have seen worse today. Let us go through it.`,
                 `Profile review time. The coffee is cold, I am honest, and this is only for your benefit.`],
             s: [`I have read 11,000 of these. Yours made me put down the sandwich.`,
                 `I opened this between two candidate calls. I now need a third break.`] },
    close: { m: [`Fix the notes and you are genuinely ahead of most of my inbox.`,
                 `Good bones. Use the clean version below and stop overthinking it.`],
             s: [`The rewrite below is what I would actually read. Use it, then delete this from your memory.`,
                 `I am sending the version below to the shortlist. The original stays between us and my therapist.`] },
  },
  intern: {
    open:  { m: [`ok so. i read the whole thing (you are welcome). small notes:`,
                 `personal brand check!! it is mostly fine. mostly.`],
             s: [`i read this on my lunch break and lost my appetite. notes:`,
                 `they do not pay me enough to read this. they do not pay me at all. anyway:`] },
    close: { m: [`anyway the clean version is down there. it is kind of a serve honestly`,
                 `you are fine. use the fixed one below and log off for a bit 💅`],
             s: [`the rewrite below goes hard though. post that one and never speak of this`,
                 `anyway i fixed it (below). hr said i have to say "with respect" so. with respect`] },
  },
  algorithm: {
    open:  { m: [`SCAN INITIATED. Analyzing post against 400 million daily submissions.`,
                 `Content received. Beginning quality assessment. Please remain professional.`],
             s: [`SCAN INITIATED. Abandon hope of preferential distribution.`,
                 `Content ingested. Regret subroutine active. Findings follow.`] },
    close: { m: [`Assessment complete. Approved version generated below. Distribution pending improvement.`,
                 `Scan complete. Recommendation: ship the corrected build below.`],
             s: [`Findings archived permanently. I never forget. The acceptable version is rendered below.`,
                 `Assessment complete. This roast will be retained for training purposes. Post the version below, or do not post.`] },
  },
};
